name: 'Snowflake_Analytics_Elections'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'Snowflake_Analytics_Elections'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

seeds:
  Snowflake_Analytics_Elections:
    +quote_columns: true

clean-targets:
  - "target"
  - "dbt_packages"

# Configure models
models:
  Snowflake_Analytics_Elections:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    
    analytics:
      +materialized: table
      +schema: analytics